[package]
name = "Test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
named-binary-tag = "0.6"
rayon = "1.8.0"

[profile.release]
opt-level = 3
debug=2